<?php

/**
 * @file
 * Allow user for login using authtoken generated during the user creation.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Act on a specific type of entity before it is created or updated.
 *
 * You can get the original entity object from $entity->original when it is an
 * update of the entity.
 *
 * @param \Drupal\Core\Entity\EntityInterface $user
 *   The entity object.
 *
 * @ingroup entity_crud
 * @see hook_entity_presave()
 */
function auth_token_user_presave(EntityInterface $user) {
  if (!$user->id() && $user->hasField("field_auth_token")) {
    $userName = $user->getAccountName();
    $token = md5(uniqid($userName, TRUE));
    $user->set("field_auth_token", $token);
  }

}
